
GET  http://localhost:3003/api/blogs/
Content-Type: application/json
###

POST http://localhost:3003/api/blogs/
Content-Type: application/json

 {
      "title": "React patterns",
      "author": "Benjamin Parker",
      "url": "https://reactpatterns.com/",
      "likes": "7"
    }

###
PUT http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "name": "Trish",
    "number": "12377777777777"
}
###
DELETE   http://localhost:3003/api/blogs/606773a10410627deccb21d0
# Content-Type: application/json
###
PUT http://localhost:3003/api/blogs/6022f56eecd0e6f186b11db5
Content-Type: application/json

 {
    "likes": 4000,
    "title": "I love to code",
    "author": "Sam Parker",
    "url": "",
    "id": "6022f56eecd0e6f186b11db5"
  }
